name: Push to CMS
on:
  workflow_call:
    inputs:
      problems:
        description: 'File path. Ex. "Day1/Sample"'
        default: ''
        type: string
      first:
        description: 'first push to CMS?'
        default: false
        type: boolean
      
jobs:
  push:
    runs-on: [self-hosted]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: gogo
        run: |
          set -e
          for prob in ${{ inputs.problems }}; do 
            if [ ! -d "${prob}" ]; then
              echo "'${prob}' Not Found"
              exit 1
            fi
            cd "${prob}"
            tps gen
            tps export CMS -a none -o cms_dir
            if [ "${{ inputs.first }}" = "true" ]; then
              cmsImportTask cms_dir
            else
              cmsImportTask cms_dir --update
            fi
            rm -rf cms_dir
            cd ..
          done