name: Push to CMS
on:
  workflow_call:
    inputs:
      problems:
        description: 'File path. Ex. "Day1/Sample"'
        default: ''
        type: string
      contestID:
        description: 'Contest id (-c). Leave empty to not attach to a contest.'
        default: ''
        required: false
        type: string
      prefix:
        description: 'Task name prefix (-p). Leave empty for no prefix.'
        default: ''
        required: false
        type: string

jobs:
  push:
    runs-on: [self-hosted]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: gogo
        run: |
          set -e
          args=()
          if [ -n "${{ inputs.contestID }}" ]; then
            args+=(-c "${{ inputs.contestID }}")
          fi
          if [ -n "${{ inputs.prefix }}" ]; then
            args+=(-p "${{ inputs.prefix }}")
          fi
          for prob in ${{ inputs.problems }}; do
            if [ ! -d "${prob}" ]; then
              echo "'${prob}' Not Found"
              exit 1
            fi
            cd "${prob}"
            tps gen
            tps export CMS 1 -a none -o cms_dir
            cmsImportTask cms_dir --update "${args[@]}"
            rm -rf cms_dir
            cd ..
          done
